#!/bin/bash

rm openmp_sum.txt
./serial -n 5000 -no -s openmp_sum.txt
export OMP_NUM_THREADS=1
./openmp -n 5000 -no -s openmp_sum.txt
export OMP_NUM_THREADS=2
./openmp -n 5000 -no -s openmp_sum.txt
export OMP_NUM_THREADS=4
./openmp -n 5000 -no -s openmp_sum.txt
export OMP_NUM_THREADS=8
./openmp -n 5000 -no -s openmp_sum.txt
export OMP_NUM_THREADS=16
./openmp -n 5000 -no -s openmp_sum.txt
export OMP_NUM_THREADS=2
./openmp -n 10000 -no -s openmp_sum.txt
export OMP_NUM_THREADS=4
./openmp -n 20000 -no -s openmp_sum.txt
export OMP_NUM_THREADS=8
./openmp -n 40000 -no -s openmp_sum.txt
export OMP_NUM_THREADS=16
./openmp -n 80000 -no -s openmp_sum.txt
./autograder -v openmp -s openmp_sum.txt
